/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Billboard, useGLTF, useTexture } from "@react-three/drei";
import ImagePin from "../ImagePin";

const LocationPin = (props) => {
    const { nodes } = useGLTF("/glb/final/location-pin.glb");
    const texture = useTexture('/textures/final/road-baked-test.jpg')

    if (!props.imageSrc) return null

    console.log(props)

    return (
        <group dispose={null}>

            <ImagePin {...props}
                rotation={[0, Math.PI / 2, 0]} />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Location_sign_06v.geometry}
                position={props.position}
                rotation={[0, 0, 0]}
                scale={0.5}
            >
                <meshStandardMaterial
                    map={texture}
                    map-flipY={false}
                    map-generateMipmaps={true}
                    map-anisotropy={16}
                />
            </mesh>

        </group>
    );
}

useGLTF.preload("/glb/final/location-pin.glb");
export default LocationPin;