/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

export function Plane(props) {
  const { nodes } = useGLTF("/glb/final/plane.glb");
  const texture = useTexture("/textures/final/plane-baked.jpg");
  return (
    <group {...props} dispose={null}>
      <mesh scale={0.25} geometry={nodes.Plane.geometry}>
        <meshStandardMaterial
          map={texture}
          map-flipY={false}
          map-generateMipmaps={true}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/glb/final/plane.glb");
