/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { isMobile } from "react-device-detect";

const RoadFinal = (props) => {
  const { nodes } = useGLTF("/glb/final/road-with-y.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow={!isMobile}
        receiveShadow
        rotation={[0, -Math.PI * 0.5, 0]}
        geometry={nodes.BezierCurve.geometry}
        position={[-4.3, -2.73, 3]}
        scale={0.635}
      >
        <meshStandardMaterial color={0x9c0f00} metalness={0} roughness={1} />
      </mesh>
    </group>
  );
};

useGLTF.preload("/glb/final/road-with-y.glb");

export default RoadFinal;
