/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { isMobile } from "react-device-detect";
import React from "react";
import { useGLTF, useTexture } from "@react-three/drei";

const Road = (props) => {
  const { nodes } = useGLTF("/glb/final/road-thicker.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow={isMobile ? false : true}
        receiveShadow={false}
        // scale={0.25}
        scale={0.635}
        rotation={[0, -Math.PI * 0.5, 0]}
        geometry={nodes.BezierCurve.geometry}
        // position={[0, -1.025, 0]}
        position={[-4.58, 1.13, 3.24]}
      >
        <meshStandardMaterial
          // map={texture}
          color={0x9c0f00}
          roughness={1}
          metalness={0}
          // map-flipY={false}
          // map-generateMipmaps={true}
          // map-anisotropy={8}
        />
      </mesh>
    </group>
  );
};

useGLTF.preload("/glb/final/road-new.glb");

export default Road;
