/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const RoadFinal = (props) => {
  const { nodes } = useGLTF("/glb/final/road-with-y-with-nubs.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow={!props.isMobile}
        rotation={[0, -Math.PI * 0.5, 0]}
        geometry={nodes.Sphere001.geometry}
        // position={[-4.3, -2.73, 3]}
        // position={[2.92, 0.141, 7.575]}
        position={[-4.35, 1.025, 3.04]}
        scale={0.099 * 0.635}
      >
        <meshStandardMaterial color={0x9c0f00} metalness={0} roughness={1} />
      </mesh>
    </group>
  );
};

useGLTF.preload("/glb/final/road-with-y-with-nubs.glb");

export default RoadFinal;
