/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF, useTexture } from "@react-three/drei";

const TopAltFinal = (props) => {
  const { nodes } = useGLTF("/glb/final/top.glb");

  const texture =
    window.innerWidth < 1023
      ? useTexture("/textures/final/baked-brit-mobile.webp")
      : useTexture("/textures/final/baked-brit.webp");

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow={false}
        receiveShadow={true}
        geometry={nodes.EXPORT_GOOGLE_SAT_WM.geometry}
        position={[0.46, 0.9, 1.195]}
        rotation={[0, Math.PI * 1.5, 0]}
        scale={[0.635 * 0.00005, 0.7 * 0.00005, 0.635 * 0.00005]}
      >
        <meshStandardMaterial
          map={texture}
          map-flipY={false}
          map-generateMipmaps={true}
          map-anisotropy={props.isMobile ? 1 : 8}
        />
      </mesh>
    </group>
  );
};

useGLTF.preload("/glb/final/top.glb");

export default TopAltFinal;
