/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

export default function Edges(props) {
  // const edgeTexture = useTexture("/textures/edges-baked.jpg");
  const { nodes } = useGLTF("/glb/edges.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        side={THREE.DoubleSide}
        geometry={nodes.EXPORT_GOOGLE_SAT_WM.geometry}
        material={nodes.EXPORT_GOOGLE_SAT_WM.material}
        position={[0, 0.0, 0]}
        scale={0.00005}
      >
        <meshStandardMaterial 
        // map={edgeTexture}
          color={0xefefef} 
          side={THREE.DoubleSide}
          // map-flipY={false}
          />
      </mesh>
    </group>
  );
}

useGLTF.preload("/glb/edges.glb");
