/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";

export default function Edges(props) {
  const { nodes, materials } = useGLTF("/glb/edges.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.EXPORT_GOOGLE_SAT_WM.geometry}
        // material={nodes.EXPORT_GOOGLE_SAT_WM.material}
        position={[0, 0.0, 0]}
        scale={0.00005}
      >
        <meshStandardMaterial color={0xafafaf} side={THREE.DoubleSide} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/glb/edges.glb");
