/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { useControls } from "leva";

export default function IceFieldsDecimated(props) {
  const { nodes } = useGLTF("/glb/ice-fields-no-edges-decimated.glb");
  // const iceFieldsTexture = useTexture("/textures/baked-no-alpha.jpg");
  const iceFieldsTexture = useTexture("/textures/test.jpg");
  const green1 = useTexture("/textures/green/baked-green-1.jpg");

  const green2 = useTexture("/textures/green/baked-green-2.jpg");
  const green3 = useTexture("/textures/green/baked-green-3.jpg");
  const green4 = useTexture("/textures/green/baked-green-4.jpg");
  const green5 = useTexture("/textures/green/baked-green-5.jpg");
  const green6 = useTexture("/textures/green/baked-green-6.jpg");
  const green7 = useTexture("/textures/green/baked-green-7.jpg");
  const green4Redux = useTexture("/textures/green/baked-green-4-redux-2.jpg");
  const green7Redux = useTexture("/textures/green/baked-green-7-redux.jpg");
  const sarahs = useTexture("/textures/green/baked-sarahs.jpg");

  // const { texture } = useControls({
  //   texture: {
  //     value: green4,
  //     // 1 looks ok
  //     // 2 might be a bit much
  //     // 4 looks good
  //     // 5 looks good

  //     options: {
  //       green1,
  //       green2,
  //       green3,
  //       green4,
  //       green5,
  //       green6,
  //     },
  //   },
  // });

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.EXPORT_GOOGLE_SAT_WM002.geometry}
        position={[0, 0.157, 0]}
        scale={4}
      >
        <meshStandardMaterial
          map={green4Redux}
          // side={THREE.DoubleSide}
          roughness={1}
          metalness={0}
          map-flipY={false}
          // normalMap={iceFieldsTexture} // TODO: if needed
          // map-anisotropy={32}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/glb/ice-fields-no-edges-decimated.glb");
