/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
// import { editable as e } from "@theatre/r3f";

export default function LocationPin(props) {
  const { nodes, materials } = useGLTF("/glb/location-pin.glb");
  return (
    <group {...props} dispose={null} theatreKey="Pin">
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials["Pin Red"]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.1, 0.02, 0.1]}
      />
    </group>
  );
}

useGLTF.preload("/glb/location-pin.glb");
