/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { editable as e } from "@theatre/r3f";

export default function LocationPin(props) {
  const { nodes, materials } = useGLTF("/glb/location-pin.glb");
  return (
    <e.group {...props} dispose={null} theatreKey="Pin">
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials["Pin Red"]}
        position={[0, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.2, 0.0394, 0.2]}
      />
    </e.group>
  );
}

useGLTF.preload("/glb/location-pin.glb");
