/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
// import { editable as e } from "@theatre/r3f";

export default function LocationPin(props) {
  const { nodes } = useGLTF("/glb/location-pin.glb");
  return (
    <group {...props} dispose={null} theatreKey="Pin">
      <mesh
        castShadow
        geometry={nodes.Cylinder.geometry}
        material={
          new THREE.MeshStandardMaterial({
            color: 0xff0000,
            roughness: 1.0,
          })
        }
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.05, 0.01, 0.05]}
      ></mesh>
    </group>
  );
}

useGLTF.preload("/glb/location-pin.glb");
