/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Path(props) {
  const { nodes, materials } = useGLTF("/glb/test-path.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath.geometry}
        material={nodes.NurbsPath.material}
        position={[10.065, 1.149, 2.158]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 0.313, 1]}
      />
    </group>
  );
}

useGLTF.preload("/glb/test-path.glb");

export default Path;
