/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { useControls } from "leva";

export default function Plane(props) {
  const planeTexture = useTexture("/textures/plane-baked.jpg");
  const { nodes } = useGLTF("/glb/plane.glb");
  
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        rotation={[0, 1.571, 0]}
        position={[0, -0.7, 0]}
        scale={105}
      >
        <meshStandardMaterial
          map={planeTexture}
          side={THREE.DoubleSide}
          roughness={1}
          metalness={0}
          map-flipY={false}
          
          // normalMap={iceFieldsTexture} // TODO: if needed
          map-anisotropy={32}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/glb/plane.glb");
